# Generated by Django 5.0.14 on 2026-07-29 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_identificacao", models.CharField(blank=True, max_length=254)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("login_sucesso", "Login realizado"),
                            ("login_falha", "Tentativa de login malsucedida"),
                            ("logout", "Logout"),
                            ("bloqueio_tentativas", "Conta bloqueada por tentativas"),
                            ("acesso_negado", "Acesso negado a recurso protegido"),
                            ("senha_alterada", "Senha alterada"),
                            (
                                "senha_reset_solicitado",
                                "Recuperação de senha solicitada",
                            ),
                            ("acesso_dado_pessoal", "Acesso a dado pessoal"),
                            ("criacao", "Registro criado"),
                            ("alteracao", "Registro alterado"),
                            ("exclusao", "Registro excluído"),
                            ("exportacao_dados", "Dados do titular exportados"),
                            ("anonimizacao", "Dados do titular anonimizados"),
                            ("consentimento_registrado", "Consentimento registrado"),
                            ("consentimento_revogado", "Consentimento revogado"),
                        ],
                        max_length=40,
                    ),
                ),
                ("objeto_tipo", models.CharField(blank=True, max_length=100)),
                ("objeto_id", models.CharField(blank=True, max_length=64)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("envolve_dado_sensivel", models.BooleanField(default=False)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to="core.tenant",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoria",
                "verbose_name_plural": "Registros de Auditoria",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["-criado_em"], name="auditoria_r_criado__51412a_idx"
                    ),
                    models.Index(
                        fields=["acao", "-criado_em"],
                        name="auditoria_r_acao_9a738e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "-criado_em"],
                        name="auditoria_r_tenant__36f9df_idx",
                    ),
                    models.Index(
                        fields=["objeto_tipo", "objeto_id"],
                        name="auditoria_r_objeto__e58c07_idx",
                    ),
                    models.Index(
                        fields=["envolve_dado_sensivel", "-criado_em"],
                        name="auditoria_r_envolve_2c858e_idx",
                    ),
                ],
            },
        ),
    ]
