# Generated by Django 5.0.14 on 2026-07-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "segmento",
                    models.CharField(
                        choices=[
                            ("fundo_social", "Fundo Social / Prefeitura"),
                            ("home_care", "Home Care"),
                            ("locadora", "Locadora"),
                            ("hospital", "Hospital"),
                            ("ong", "ONG"),
                        ],
                        default="fundo_social",
                        max_length=20,
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=120)),
                ("uf", models.CharField(blank=True, max_length=2)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("contato", models.CharField(blank=True, max_length=150)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": ["nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="fornecedor",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nome"), name="fornecedor_unico_por_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="unidade",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nome"), name="unidade_unica_por_tenant"
            ),
        ),
    ]
