# Generated by Django 5.0.14 on 2026-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidade",
            name="cidade",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="unidade",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="unidade",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidade",
            name="responsavel",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="unidade",
            name="telefone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="unidade",
            name="tipo",
            field=models.CharField(
                blank=True,
                help_text="Ex.: Matriz, Filial, Loja, Fundo Social — texto livre, varia por segmento.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="unidade",
            name="uf",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
