# Generated by Django 5.0.14 on 2026-08-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_seed_modulos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="dpo_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail do Encarregado (DPO)"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="dpo_nome",
            field=models.CharField(
                blank=True,
                help_text="Pessoa responsável por atender solicitações de titulares deste tenant (LGPD Art. 41).",
                max_length=150,
                verbose_name="Nome do Encarregado (DPO)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="dpo_telefone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Telefone do Encarregado (DPO)"
            ),
        ),
    ]
