# Generated by Django 5.0.14 on 2026-08-03 12:54

import core.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tenant_dpo_email_tenant_dpo_nome_tenant_dpo_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Aparece nas etiquetas patrimoniais dos ativos.",
                null=True,
                upload_to="tenants/logos/",
                validators=[core.validadores.validar_upload_imagem],
                verbose_name="Logotipo",
            ),
        ),
    ]
