# Generated by Django 5.0.14 on 2026-07-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_seed_papeis"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="unidades",
            field=models.ManyToManyField(
                blank=True,
                help_text="Unidades que este usuário pode operar/visualizar. Só tem efeito para Gestor/Funcionário — Admin sempre enxerga todas as unidades do tenant, independentemente do que estiver marcado aqui (docs/features/identificacao-patrimonial-e-unidades.md).",
                related_name="usuarios_permitidos",
                to="core.unidade",
            ),
        ),
    ]
