# Generated by Django 5.0.14 on 2026-07-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0002_initial"),
        ("beneficiarios", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacaoTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("confirmacao_emprestimo", "Confirmação de empréstimo"),
                            ("aviso_7_dias", "Aviso 7 dias antes do vencimento"),
                            ("vencimento", "Vencimento hoje"),
                            ("atraso", "Em atraso"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                (
                    "corpo_texto",
                    models.TextField(
                        help_text="Variáveis disponíveis: {beneficiario}, {ativo}, {codigo}, {data_prevista}, {dias}."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Notificação",
                "verbose_name_plural": "Templates de Notificação",
            },
        ),
        migrations.CreateModel(
            name="NotificacaoEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("email", "Email")],
                        max_length=10,
                    ),
                ),
                ("destinatario", models.CharField(max_length=150)),
                ("corpo_renderizado", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviado", "Enviado"),
                            ("falhou", "Falhou"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("tentativas", models.PositiveIntegerField(default=0)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="beneficiarios.beneficiario",
                    ),
                ),
                (
                    "movimentacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificacoes",
                        to="ativos.movimentacao",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envios",
                        to="notificacoes.notificacaotemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação Enviada",
                "verbose_name_plural": "Notificações Enviadas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="notificacaotemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "tipo"), name="notificacaotemplate_unico_por_tenant"
            ),
        ),
    ]
