# Generated by Django 5.0.14 on 2026-07-28 16:03

import ativos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiarios", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcategoriaAtivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Subcategoria de Ativo",
                "verbose_name_plural": "Subcategorias de Ativo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaAtivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Ativo",
                "verbose_name_plural": "Categorias de Ativo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patrimonio", models.CharField(max_length=50)),
                (
                    "qr_token",
                    models.CharField(
                        default=ativos.models.gerar_qr_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("fabricante", models.CharField(blank=True, max_length=100)),
                ("numero_serie", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("emprestado", "Emprestado"),
                            ("reservado", "Reservado"),
                            ("manutencao", "Em Manutenção"),
                            ("higienizacao", "Em Higienização"),
                            ("baixado", "Baixado"),
                            ("extraviado", "Extraviado"),
                            ("inativo", "Inativo"),
                        ],
                        default="disponivel",
                        max_length=20,
                    ),
                ),
                ("data_aquisicao", models.DateField(blank=True, null=True)),
                ("vida_util_meses", models.PositiveIntegerField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ativos",
                        to="core.fornecedor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ativos",
                        to="core.unidade",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ativos",
                        to="ativos.categoriaativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="DetalheEmprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prazo_dias", models.PositiveIntegerField()),
                ("data_prevista_devolucao", models.DateField()),
                (
                    "assinatura_tipo",
                    models.CharField(
                        choices=[
                            ("fisica", "Física (padrão)"),
                            ("digital", "Digital (módulo opcional)"),
                        ],
                        default="fisica",
                        max_length=10,
                    ),
                ),
                (
                    "assinatura_arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="assinaturas/%Y/%m/"
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimos",
                        to="beneficiarios.beneficiario",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhe de Empréstimo",
                "verbose_name_plural": "Detalhes de Empréstimo",
            },
        ),
        migrations.CreateModel(
            name="DetalheManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=255)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes",
                        to="core.fornecedor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhe de Manutenção",
                "verbose_name_plural": "Detalhes de Manutenção",
            },
        ),
        migrations.CreateModel(
            name="FotoAtivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("lateral", "Lateral"),
                            ("traseira", "Traseira"),
                            ("etiqueta", "Etiqueta de Patrimônio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("arquivo", models.ImageField(upload_to="ativos/fotos/%Y/%m/")),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="ativos.ativo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do Ativo",
                "verbose_name_plural": "Fotos do Ativo",
            },
        ),
        migrations.CreateModel(
            name="FotoMovimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("frontal", "Frontal"),
                            ("lateral", "Lateral"),
                            ("detalhe", "Detalhe"),
                            ("etiqueta", "Etiqueta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("arquivo", models.ImageField(upload_to="movimentacoes/fotos/%Y/%m/")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto da Movimentação",
                "verbose_name_plural": "Fotos da Movimentação",
            },
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("emprestimo", "Empréstimo"),
                            ("devolucao", "Devolução"),
                            ("renovacao", "Renovação"),
                            ("transferencia", "Transferência"),
                            ("reserva", "Reserva"),
                            ("manutencao", "Manutenção"),
                            ("retorno_manutencao", "Retorno de Manutenção"),
                            ("higienizacao", "Higienização"),
                            ("baixa", "Baixa Patrimonial"),
                            ("extravio", "Extravio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "status_anterior",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("emprestado", "Emprestado"),
                            ("reservado", "Reservado"),
                            ("manutencao", "Em Manutenção"),
                            ("higienizacao", "Em Higienização"),
                            ("baixado", "Baixado"),
                            ("extraviado", "Extraviado"),
                            ("inativo", "Inativo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("emprestado", "Emprestado"),
                            ("reservado", "Reservado"),
                            ("manutencao", "Em Manutenção"),
                            ("higienizacao", "Em Higienização"),
                            ("baixado", "Baixado"),
                            ("extraviado", "Extraviado"),
                            ("inativo", "Inativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dados_especificos", models.JSONField(blank=True, default=dict)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="ativos.ativo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes",
                        to="core.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-data_hora"],
            },
        ),
    ]
