# Generated by Django 5.0.14 on 2026-07-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fotomovimentacao",
            name="movimentacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotos",
                to="ativos.movimentacao",
            ),
        ),
        migrations.AddField(
            model_name="detalhemanutencao",
            name="movimentacao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalhe_manutencao",
                to="ativos.movimentacao",
            ),
        ),
        migrations.AddField(
            model_name="detalheemprestimo",
            name="movimentacao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalhe_emprestimo",
                to="ativos.movimentacao",
            ),
        ),
        migrations.AddField(
            model_name="subcategoriaativo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="ativos.categoriaativo",
            ),
        ),
        migrations.AddField(
            model_name="subcategoriaativo",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ativo",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ativos",
                to="ativos.subcategoriaativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriaativo",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nome"), name="categoria_ativo_unica_por_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategoriaativo",
            constraint=models.UniqueConstraint(
                fields=("categoria", "nome"),
                name="subcategoria_ativo_unica_por_categoria",
            ),
        ),
        migrations.AddConstraint(
            model_name="ativo",
            constraint=models.UniqueConstraint(
                fields=("tenant", "patrimonio"),
                name="ativo_patrimonio_unico_por_tenant",
            ),
        ),
    ]
