# Generated by Django 5.0.14 on 2026-07-29 06:15

import core.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ativos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalheemprestimo",
            name="assinatura_arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assinaturas/%Y/%m/",
                validators=[core.validadores.validar_upload],
            ),
        ),
        migrations.AlterField(
            model_name="fotoativo",
            name="arquivo",
            field=models.ImageField(
                upload_to="ativos/fotos/%Y/%m/",
                validators=[core.validadores.validar_upload_imagem],
            ),
        ),
        migrations.AlterField(
            model_name="fotomovimentacao",
            name="arquivo",
            field=models.ImageField(
                upload_to="movimentacoes/fotos/%Y/%m/",
                validators=[core.validadores.validar_upload_imagem],
            ),
        ),
    ]
