# Generated by Django 5.0.14 on 2026-07-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ativos", "0003_alter_detalheemprestimo_assinatura_arquivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaativo",
            name="prefixo",
            field=models.CharField(
                blank=True,
                help_text="Ex.: CAD para Cadeira de Rodas. Em branco, é derivado do nome da categoria.",
                max_length=10,
            ),
        ),
    ]
