# Generated by Django 5.0.14 on 2026-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ativos", "0005_etiquetas_transferencia_e_unidade_obrigatoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalheemprestimo",
            name="caucao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor retido como caução, conferido na devolução.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="detalheemprestimo",
            name="percentual_multa_atraso_dia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual sobre o valor total do período, cobrado por dia de atraso na devolução.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="detalheemprestimo",
            name="valor_diaria",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor cobrado por dia de locação.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
