# Generated by Django 5.0.14 on 2026-07-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_relacao",
                    models.CharField(
                        choices=[
                            ("beneficiario", "Beneficiário"),
                            ("paciente", "Paciente"),
                            ("cliente", "Cliente"),
                        ],
                        default="beneficiario",
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14)),
                ("rg", models.CharField(blank=True, max_length=20)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "contato_emergencia_nome",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "contato_emergencia_telefone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "contato_emergencia_parentesco",
                    models.CharField(blank=True, max_length=50),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiário",
                "verbose_name_plural": "Beneficiários",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoBeneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rg", "RG"),
                            ("cpf", "CPF"),
                            ("comprovante_residencia", "Comprovante de Residência"),
                            ("receita_medica", "Receita Médica"),
                            ("laudo", "Laudo"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to="beneficiarios/documentos/%Y/%m/"),
                ),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="beneficiarios.beneficiario",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Beneficiário",
                "verbose_name_plural": "Documentos do Beneficiário",
            },
        ),
        migrations.AddConstraint(
            model_name="beneficiario",
            constraint=models.UniqueConstraint(
                fields=("tenant", "cpf"), name="beneficiario_cpf_unico_por_tenant"
            ),
        ),
    ]
