# Generated by Django 5.0.14 on 2026-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiario",
            name="anonimizado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando os dados identificáveis foram removidos a pedido do titular (Art. 18 VI).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="base_legal",
            field=models.CharField(
                choices=[
                    ("consentimento", "Consentimento do titular (Art. 7º I / 11 I)"),
                    ("obrigacao_legal", "Obrigação legal ou regulatória (Art. 7º II)"),
                    ("politica_publica", "Execução de política pública (Art. 7º III)"),
                    ("tutela_saude", "Tutela da saúde (Art. 11 II 'f')"),
                    ("execucao_contrato", "Execução de contrato (Art. 7º V)"),
                ],
                default="consentimento",
                help_text="Hipótese legal que autoriza o tratamento dos dados deste titular.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="consentimento_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento em que o titular consentiu. Obrigatório quando a base legal é consentimento.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="consentimento_revogado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Revogação do consentimento (Art. 8º §5º). Não apaga o histórico operacional já constituído.",
                null=True,
            ),
        ),
    ]
