# Generated by Django 5.0.14 on 2026-07-29 06:15

import core.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beneficiarios",
            "0002_beneficiario_anonimizado_em_beneficiario_base_legal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentobeneficiario",
            name="arquivo",
            field=models.FileField(
                upload_to="beneficiarios/documentos/%Y/%m/",
                validators=[core.validadores.validar_upload],
            ),
        ),
    ]
