# Generated by Django 5.0.14 on 2026-07-30 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiarios", "0003_alter_documentobeneficiario_arquivo"),
        ("core", "0002_unidade_cidade_unidade_email_unidade_observacoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiario",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidade que atende este titular. Em branco, fica visível a toda a organização.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiarios",
                to="core.unidade",
            ),
        ),
    ]
